log_dir: "log"
sounds_dir: "sounds"
startup_sound: "startup.wav"
shutdown_sound: "shutdown.wav"
shutdown_button_pin: 27
switch_sound: "switch_sound.wav"
switch_button_pin: 17
buttons:
  "26": cow
  "13": bird
  "6": cock
  "5": horse
  "12": duck
  "4": sheep
